### ISSUE TITLE
Is there any chance to use linter-javac together with standalone files?

### ISSUE THREAD

**Issue by efkan** [AtomLinter/linter-javac#105]
Hello,

I wonder that is there any chance to use `linter-javac` together with a React-Native project. 
I mean does it works for standalone java files? If so, how can I do?

Actually I asked on [stackoverflow](http://stackoverflow.com/q/38772865/3765109) this question a couple of days ago. Unfortunately there is no answer yet.

For instance I have a folder as `c:\JavaFiles` which contains several java files.

**Comment by florianb** [comment]
Hi @efkan -- thank you for getting in touch. I hope i got your issue right.

I guess you're using the wrong Linter, linter-javac is meant to lint Java-files/projects. React Native is based on JavaScript. You should be able to lint your React Native project with a JS-linter like [linter-eslint](https://atom.io/packages/linter-eslint) (even though i haven't worked on a React Native project, yet).

I answered the corresponding SO-question, too.

I will close this issue for now -- i will reopen it if you feel this isn't solved! 💐

**Comment by efkan** [comment]
`React-Native` allows me to develop my own [native `java` modules](http://facebook.github.io/react-native/docs/native-modules-android.html). And I've been developing Java modules for 4 months. I really need to use something like `linter-javac`. 

Because at every time I have to build the package with unaware the mistakes of syntax or something like it. And it takes one or two minutes at ever time unfortunately.

**Comment by florianb** [comment]
Thanks for clarification @efkan - i didn't know that.

Linter-javac shouldn't need any special configuration to "start" working. In its default configuration it just runs "javac" from the command line which is something you should check. I guess you know that linter-javac currently lints onSave only, which means, to invoke the first lint you'd need to save the current java-file.

If this doesn't help i'd like to ask you enabling verbose logging and post the results.

**Comment by efkan** [comment]
I really thank you for dealing with a novice like me :)

I had configured my `config.cson` file according to the [guide](https://github.com/AtomLinter/linter-javac#settings). But I don't have any knowledge about java development environments.

I'm sure I did something wrong. For instance I don't have a `.classpath` file.

It appears like:
```
  "linter-javac":
    additionalClasspaths: "C:\\Users\\Efkan"
    additionalJavacOptions: "-verbose -d C:\\java-class-cache"
    javaExecutablePath: "javac"
```

And my configuration screenshot:

![adsiz](https://cloud.githubusercontent.com/assets/6974198/17479742/eeeefc18-5d7c-11e6-9638-35638a0fc165.png)

**Comment by efkan** [comment]
Thank you! 

I had to read the all explanation! and I had seen the `Verbose Logging`.

Everything works perfect!

**Comment by florianb** [comment]
No worries - I wasn't aware of React Native's Java-link-in-capabilities.. ;D

Okay, first of all, you shouldn't need to tell linter-javac any Additional Parameters. F.e. the Additional Classpaths as well as the Additional Javac Options are implemented to give people with unusual configurations the option to override the defaults.

1. You should start configuring linter-javac by resetting it to the defaults (just clear Additional Classpaths and the Additional Javac Options).

> (Without knowing how used you're to the Atom environment it is not necessary to configure linter-javac through the config.cson, we tried to expose every important attribute through the settings-GUI. I do not configure linter-javac throgh any cson-files either.)

2. Now check the Option "Verbose Logging" -- this will verbosely log the activity of linter-javac into the console (which you may open by pressing `Control + Shift + I` [which should be the Windows Shortcut, otherwise use the Command: Window: Toggle Dev Tools]).

3. Then open the java file you'd like to lint and press save. This will invoke a "lint" and should end in some notifications in the console.

**Comment by florianb** [comment]
Just got you're response.. Happy it works for you -- i will leave my answer for other people landing here by some research. 😃

**Comment by efkan** [comment]
Thanks again and again :)
