### ISSUE TITLE
Allow Choice in Generating Class file alongside Source File

### ISSUE THREAD

**Issue by bluescreen10** [AtomLinter/linter-javac#35]
Since linter-javac invokes the compiler if the file passes linter it would generate a .class file. To prevent that linter-javac needs to create a temporary folder and use the "-d" option of javac to place compiled classes and then remove the .tmp folder.

**Comment by k2b6s9j** [comment]
/cc @steelbrain

Mind taking this?

**Comment by steelbrain** [comment]
Sure

**Comment by kepler0** [comment]
I would like to confirm that I have encountered this myself in a Java project I was working on.

**Comment by steelbrain** [comment]
@kepler0 If you want this to be resolved quickly, please do take it over

**Comment by kepler0** [comment]
I've got more time now, I'll take this soon.

**Comment by steelbrain** [comment]
:+1:

**Comment by ALEXMORF** [comment]
Is there an estimated date on when this functionality will be added?

**Comment by keskiju** [comment]
I think removing classes after linting should be optional, because automatically compiled classes can be useful in many ways, e.g. autocompleting using classes, developing whilst JVM is running and reloading changed classes with spring-loaded, etc.

Javac configuration should be project specific, imho. Perhaps a .javac file placed at the project root dir? It would also solve #2, since then you can freely give additional project specific flags to javac, e.g. source file encoding and target java version.

**Comment by florianb** [comment]
Are there any news on this? :)

**Comment by florianb** [comment]
I'm taking over that issue and going to investigate this.

I guess adding a choice in the configuration-settings to optional cleaning up any temporary content would help all involved parties?

**Comment by ALEXMORF** [comment]
Yes I think so. This functionality will definitely help all involved parties.

**Comment by keskiju** [comment]
This issue probably exists mainly because linter-javac doesn't provide the -d switch. It is annoying that class files are generated to the same directory where your source files are located. But once the -d switch has been implemented, it is probably not necessary to delete classes every time after linting, and it is probably not wise either. If you always delete classes after linting, javac would have to generate them every time again and again, even those classes that haven't changed. You also cannot use them for autocompletion (autocomplete-java), hot reloading (spring-loaded) and running your app.

Most Java IDEs keep all classes compiled all the time and delete them only if manual project refresh/clean is executed by the user. I think linter-javac should operate the same way.

**Comment by florianb** [comment]
Okay, i added custom-javac-options for the pending 1.6.0-release allowing you to make use of the `-d`-option or anything else.
