### ISSUE TITLE
Project-specific classpath configuration without .classpath

### ISSUE THREAD

**Issue by florianb** [AtomLinter/linter-javac#62]
I carried the requirement to allow a project-specific classpath-configuration to a corresponding thread in the atomcommunity: https://github.com/atom-community/linter/issues/744

It turned out that it's the final consensus to provide project-specific configurations via the [project-manager plugin](https://atom.io/packages/project-manager).

Since the `.classpath`-file is originated in the Eclipse-project (you might take a look at this [reference](http://www-01.ibm.com/support/knowledgecenter/SS8S5A_6.0.5/com.ibm.curam.content.doc/ServerDeveloper/r_SERDEV_Eclipse1ClasspathFile1.html) - i didn't find a better resource) i think we should in the interest of consistency:

1. Drop the support of `.classpath`-files to avoid conflicts with the Eclipse-family (it seems that many dev-tools rely on the original `.classpath`-format) with the release of the milestone 1.7.0 or later.
2. Document the use of the project-manager-plugin to define custom classpaths.
3. Warn the user sufficiently early (> 6 weeks) that the `.classpath`-functionality will change.

I would really appreciate to get any feedback or thoughts on this. :lollipop:

**Comment by keskiju** [comment]
Many linters support folder specific settings. For example with eslint you can have separate .eslintrc files for client and server directories. IMHO folder specific settings be very useful feature also for linter-javac but does project-manager plugin support that? If it doesn't, how about a folder specific .javacrc file that would contain a classpath and other javac-settings like encoding, source, etc? Linter-javac, autocomplete-java and many other java plugins would then use the same .javacrc file for folder specific javac settings.

**Comment by florianb** [comment]
The project-manager plugin allows you to set the all configuration-settings for every plugin on a per project base. That means, if you manage a project with different classpath-settings in subfolders, you'd have to open the different folders in paralell as different "projects". Then every project-directory may have a different config.

I went into the discussion with the idea adding a linter-specific configuration-mechanism, which would have allowed us to implement any fancy features we could imagine. But on the other hand it would add another point of failure and as long as we're alone with that approach we're not able to implement this use AtomLinter-wide.

And as far as i can tell there are only a few linters depending on classpath-settings.

**Comment by Arcanemagus** [comment]
Actually there is only this one that is trying to do anything like this on it's own, all other `AtomLinter/linter-*` plugins rely on their linter program to handle things like that (eg: `eslint`).

It does sound like it might be a good idea to start a discussion with other Atom packages that are using `javac` as to how to configure it and if you need a custom configuration file that you all handle in the same manner.

**Comment by florianb** [comment]
@Arcanemagus i think that's not really the case. With the introduction of the reinvented `.classpath` files (which is a concept introduced by linter-scalac) confusingly an already settled fileformat was obscured.

As the discussion in atom-community proved an overall configuration solution is considered as too obtrusive.

A java-specific-solution, which f.e. allows us to use classpath-definitions from other tools like Eclipse, Maven and so on must be considered as too complex.

I also consider trying to create a overall solution, which might fit to all java-based languages as a too big effort since 1) linter-scalac would have to at least change the `.classpath`-dependency and 2) most of the java-dependent languages introduce different mechanisms to fix redundant classpath-definitions.

**Comment by keskiju** [comment]
Classpath, source encoding, target java version, etc. are settings that should be shared among development team, and thus, should be committed to project git repository, imho. I don't know if project-manager plugin supports that. It seems that it saves settings of all projects to a single user specific projects.cson file that is located in .atom directory.

**Comment by florianb** [comment]
Using project-manager there would be the possibility putting all atom-configuration options per project in a `cson`-file. The could also go complete classpath-definitions as well as javac-command line options.

All javac-options for the linter could also go into specific `@files` which then also may be shared over a scm.

Using the project-manager plugin would in my opinion decrease our maintenance efforts.

**Comment by keskiju** [comment]
Javac settings and linter-javac settings should be kept separate, since javac settings are shared among developers, tools and scripts, but linter-javac settings plugin specific. I would just replace the current .classpath file with a javac.properties file that contains all javac settings. For example:

    d=./classes
    encoding=ISO-8859-1
    target=1.7
    classpath=./classes:./lib/*:../somemodule/classes:../anothermodule/classes

This would be very easy to implement and it has many benefits:

* Javac settings are shared among developers
* Javac settings can easily be reused by different tools and scripts (e.g. you can import javac.properties file in your ant/gradle/maven/shell script)
* You can have a project that consists of many small deployable modules that each have its own classpath and destination directory, but still no need to open each module as a separate project in Atom.
* No dependency to project-manager plugin

The javac.properties file name should be configurable in linter-javac package settings (some may prefer build.properties or something else). And user may configure project specific settings for linter-javac with project-manager plugin, if he likes.

**Comment by keskiju** [comment]
Actually build.properties would probably be better as a default filename for the file.

**Comment by florianb** [comment]
I really dislike the idea handling configuration-files on linter-plugin-level. I adds a lot of complexity in the Atom-environment (different platforms must be considered as well as different Node-versions), then parsing of text-files is no easy task as well, which would encourage the use of a third-party node-module - introducing just another dependency.

What you're describing can be made by using the [argfiles-parameter](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javac.html#commandlineargfile), this would "just" require at least one additional parameter to the javac-call.

I would at first suggest *any* user of linter-javac, to make use of the argfiles.

And i could imagine trying to figure a way out to "automatically" detect a specified file-ending and then add automatically any existing argfiles. But i'd like to add this not before the 1.7.0-release.

@keskiju, what do you say?

**Comment by keskiju** [comment]
Autocomplete-java needs to know classpath but it doesn't run javac command. Therefore even if linter-javac would use argfile, the autocomplete-java package would still have to parse that file for classpath. And same goes for build scripts and other tools.

Introducing a dependency to a third party npm module (e.g. [properties](https://www.npmjs.com/package/properties)) for parsing a standard Java properties file is not that bad, imho. But dependencies between Atom packages can be bad if they force the user. Forcing all users to use project-manager plugin for project management just doesn't sound good to me. And defining the same classpath in multiple places doesn't sound good either, since it can be really troublesome for a large project consisting of multiple modules that each have their own classpath.

**Comment by keskiju** [comment]
My main point is that classpath should be defined in such a format that can be used by different tools and scripts as widely as possible. A standard java properties file would probably be a good choice since it's a very simple format and it is supported by many java build tools out-of-the-box. By using a properties file we would also avoid polluting project with multiple separate settings files, since all build related properties can be defined in the same properties file.

**Comment by florianb** [comment]
I somehow missed that you're the Autocomplete-java developer. It's nice to have you in the discussion.

As you see in the main thread of the per-project configuration for Atom-linter, i agree with you. I prefer a a npm-dependency over a package-dependency. But since i assume that i might be the only person maintaining such a npm-package, i'd like to avoid that additional effort.

As far as i can tell, i won't get any support from the linter-devmunity (even though i didn't ask in all java-related projects).

So could you imagine to outsource the classpath-examination into a node-module?

If so i'd like to investigate if we could create something more flexible. Being able to plugin importers in for a properties file or a real `.classpath`-file.

**Comment by keskiju** [comment]
I probably should have mentioned that I'm developing autocomplete-java :) Yes, a separate node-module sounds good. I'm currently quite busy with work related projects but once I get some free time, I'll see if I can stir up a module that both autocomplete-java and linter-javac can use. At first supporting a simple properties file is probably enough. But surely support for eclipse .classpath would be nice also at some point.

**Comment by florianb** [comment]
@keskiju great! No hurry - i will prototype a npm-module for that, if you don't mind.

Maybe its also interesting for you, that as a side effect to #35, i gather a complete list of all class-files generated by javac. If these class-files are of your interest i'd consider a more generic way to obtain and manage class-references.

**Comment by keskiju** [comment]
I don't think #35 requires keeping a list of generated class files. You can probably just delete the whole target directory as suggested in the opening message of the issue.

Surely, make a prototype. Perhaps usage of the npm module could be something like this (here javaEnv is the npm module):

    const cpInfo = await javaEnv.findClasspathInfo(currentPath, projectPath);
    await lint(currentFilePath, cpInfo.getJavacParameters());

And later cleaning the project:

    await deleteDir(cpInfo.getTargetDir());

Just a quick suggestion. Sorry for the JavaScript code with all the ES7 await stuff. I've never coded in coffeescript myself :/ In coffeescript you would probably use plain promises instead of await.

**Comment by keskiju** [comment]
Actually since project may consist of multiple modules that each have their own classpath, perhaps cleaning the whole project should go like this:

    deleteDirs(javaEnv.getTargetDirs());

So basically javaEnv keeps track of all classpaths.

**Comment by florianb** [comment]
Nevermind, i only use coffeescript to get more used to it and because of its extensive use in the atom-project.

I don't mind using ES or Babel as foundation for the module. In order to keep track of the project i think we can't avoid a dependency to atom. So i'd name the module `atom-javaenv`.
I will draft the project, adding a API-proposal to talk about.

**Comment by keskiju** [comment]
Perhaps javaenv should be a atom package after all. It would serve as a base package that would provide some basic configurations and commands that other java related plugins could rely on:

* JAVA_HOME setting
* 'clean project' command that makes plugins discard all temp data (compiled class files, class dictionaries held in memory, etc)
* ...

**Comment by florianb** [comment]
@keskiju :+1: - that's all reasonable, it will be a atom-package written in ES.

I therefore close this issue and add the requirement to the next major-release: #76
