### ISSUE TITLE
Linter-javac adds >150 ms to loadtime

### ISSUE THREAD

**Issue by florianb** [AtomLinter/linter-javac#75]
That's slow as a :snail:...

**Comment by florianb** [comment]
I guess is will refactor the whole thing soon.

**Comment by keskiju** [comment]
Yeah, that is slow :) What is the current opinion on Atom community about CoffeeScript vs Babel/ES6? Is Atom community moving towards ES6 or still continuing with CoffeeScript? If you're going to refactor the whole thing anyway, perhaps Babel could be considered? It might help getting more contributions, since many Java coders are very familiar with JavaScript but only few know CoffeeScript.

**Comment by florianb** [comment]
:sweat:
I didn't recognize that connection between Java-Devs and JavaScript but i guess you're right. This would definitely raise contribution-potential.

In fact i have no clue where the coffeescript-thing goes, but i think in general ES will be the simplest thing to rely on. I think it's considerable good idea to rely on ES when refactoring.

**Comment by steelbrain** [comment]
Just a side note that most of the base linter package has been rewritten into ES6+ and everything new going forward will be in ES6+ instead of coffeescript

**Comment by florianb** [comment]
@steelbrain - thanks, then it is decided.. :dancers:

**Comment by florianb** [comment]
https://github.com/AtomLinter/linter-javac/blob/master/lib/init.coffee#L20

should be

```
require('atom-package-deps').install('linter-javac')
```

**Comment by florianb** [comment]
This issue is part of the 2.0.0-release.
