### ISSUE TITLE
Suppressing/fixing Unmappable character errors

### ISSUE THREAD

**Issue by drakecaiman** [AtomLinter/linter-javac#81]
I'm currently getting the following error from files with the © in its text:

unmappable character for encoding UTF8…

I don't have a problem compiling these files in ant, so is there a way to fix or suppress these warning in lint? Thanks!

**Comment by florianb** [comment]
Hi @drakecaiman,

i can only guess why this happens - you should try to find out with which options Ant is calling the java-compiler.

This error indicates a difference between the encoding of your java-sourcefiles and the platform-default encoding. I recommend you to find out how the source-files are encoded (assumingly `UTF8`) and consider changing the platform-encoding if it is not `UTF8`.

 It may be that adding the `-encoding UTF8`-option to the "Additional Javac Options" may solve this issue for you.

I am closing that issue since there is nothing we can do by changing the codebase of linter-javac. Thanks for getting in touch - feel free to come back to me. :candy:

**Comment by florianb** [comment]
See this list for all supported encodings: https://docs.oracle.com/javase/7/docs/technotes/guides/intl/encoding.doc.html
