### ISSUE TITLE
Not handling compilation errors from javac < 1.7

### ISSUE THREAD

**Issue by jvmock** [AtomLinter/linter-javac#86]
The current released version of linter-javac (1.8.1) appears to not capture compilation failures.  When this occurs the debug reports 0 linter messages, and the linter status reports "No issues".

At a cursory glance I didn't immediately see anything wrong with the parsing routine, however, I haven't had the opportunity to perform further testing to determine a cause.

- Compiler:
  - IBM JDK 1.6 (I know, don't hate me.  The deployment environment is forcing my hand).

**Comment by jvmock** [comment]
Ok.  So I did spend a little bit of time looking, and it appears as though the issue is in that older versions of Java (< 1.7) do not include the 'error: ' portion of the output:

    BrokenFile:54: error: invalid method declaration; return type required
      public StrigetIcon() {
             ^

So I'll leave it up to you if supporting anything < 1.7 is even worth considering.

**Comment by Arcanemagus** [comment]
Personally as Java 7 support from Oracle ended a year ago I don't think this is really worth supporting, but I'll leave it to @florianb to make a final decision as they are the maintainer of this project.

**Comment by jvmock** [comment]
The more I think about it the more I completely agree with you.  For the sake of performing the linting, I could easily configure my project to point to a newer JRE despite the targeted platform, so I'm going to go ahead and close out this issue.

**Comment by florianb** [comment]
hi @jvmock, thanks for getting in touch. I somehow agree with @Arcanemagus, but since i know the Enterprise world, i also know that Java 1.6 as well as older versions are still in use.

And in my personal opinion a missing linter option does not help changing minds but makes the world of developers even worse. And this is mainly valid for the subset of Java-developers which prefer Atom over Eclipse et al.

So i wouldn't mind integrating older versions (the performance-impact should be tending to zero), but  i would file it as a low-priority task for the next major release. Since i plan to detect Javac as well as the version in use, adding this feature wouldn't be that much work.

So if you're changing your mind, or if any other user is affected by this, too. Feel free to come back to me. :beers:

**Comment by Arcanemagus** [comment]
Should this be reopened and labelled as an enhancement @florianb?

Thankfully I don't have to deal with Java at work that much :stuck_out_tongue:.

**Comment by florianb** [comment]
A good idea @Arcanemagus - i guess we keep it closed until somebody asks for reopening. :grin:

At the beginning i felt Java-development being a torture. After exploring Gradle i decided to write my first atom-package (gradle-ci) which relieved the pain a bit. The linter makes a lot things easier, too. So having Atom at all was my salvation. :)
